name = "adminout"
main = ".output/server/index.mjs"
compatibility_date = "2023-05-27"
workers_dev = true

[site]
bucket = ".output/public"

[env.staging]
route = { pattern = "staging.adminout.net/*", zone_name = "adminout.net" }

[env.production]
route = { pattern = "adminout.net/*", zone_name = "adminout.net" }

