name: development

on:
  push:
    branches: [ '*', '*/*', '**', '!main', '!staging' ]

jobs:
  development-ci:
    environment: development
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: Test
        uses: ./.github/actions/test
