name: staging

on:
  push:
    branches:
      - staging

jobs:
  staging-ci:
    environment: staging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: Test
        uses: ./.github/actions/test

      - id: Deploy
        uses: ./.github/actions/deploy
        with:
          cf-token: ${{ secrets.CF_API_TOKEN }}
          deploy-environment: "staging"

